# Generated by Django 3.0.7 on 2021-01-27 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210127_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='doors',
        ),
    ]
